version: '3'

services:
    smartcdc_app:
        build:
            context: .
        ports:
          - 5000:5000
        container_name: "smartcdc_app"
        volumes:
            - ./:/app
            - ./docker-entrypoint-app.sh:/app/docker-entrypoint-app.sh
            - ./wsgi.py:/app/wsgi.py
        env_file:
            - .env
